Fix over pixelized images in widget
muzei/muzei pull request #725
Opened 2021-04-13 14:21 UTC by bellegarde-c

We are using cropCenter in layout. 
But cropping happens on a low quality image, this produces pixlized images when widget is landscape and image is portrait for example. 
So, do an initial square cropping before sending image to widget

2021-04-14 14:17 UTC, ianhanniballake commented
Do you have a sample picture that shows the pixelation that you're experiencing?

2021-04-14 14:30 UTC, bellegarde-c commented
![h2g2](https://user-images.githubusercontent.com/57196916/114727573-9b104500-9d3e-11eb-8241-f670bd5a7c9a.jpg)

And the pixelized result:

![before](https://user-images.githubusercontent.com/57196916/114727621-a6fc0700-9d3e-11eb-8627-35ecdbee6df6.png)

2021-04-15 04:56 UTC, ianhanniballake requested changes

2021-04-15 04:56 UTC, ianhanniballake commented on main/src/main/java/com/google/android/apps/muzei/widget/AppWidgetUpdateTask.kt
> +    when {
Instead of have a `var` declared above, use `val croppedImage = when {`

2021-04-15 04:56 UTC, ianhanniballake commented on main/src/main/java/com/google/android/apps/muzei/widget/AppWidgetUpdateTask.kt
> +                 // Image is portrait, prefer upper part
Always **center** crop the image, no matter what orientation the image is.

2021-04-15 04:56 UTC, ianhanniballake commented on main/src/main/java/com/google/android/apps/muzei/widget/AppWidgetUpdateTask.kt
> +    val widgetIsLandscape = widgetWidth >= widgetHeight
Where do you use this?

2021-04-15 04:56 UTC, ianhanniballake commented on main/src/main/java/com/google/android/apps/muzei/widget/AppWidgetUpdateTask.kt
> +    // Crop image first here for highest quality
Move this center cropping to its own method, then `createRemoteViews` can use `val scaledImage = image.centerCrop(widgetWidth, widgetHeight).scale(widgetWidth, widgetHeight)`

2021-04-25 05:28 UTC, ianhanniballake requested changes

2021-04-25 05:28 UTC, ianhanniballake commented on keystore.properties.example
> -# This is an example keystore.properties file.
Please undelete this file.

2021-04-25 05:28 UTC, ianhanniballake commented on local.properties.example
> -# This is an example local.properties file.
Please undelete this file.

2021-04-26 06:59 UTC, bellegarde-c commented on local.properties.example
> -# This is an example local.properties file.
sorry for mistake!

2021-04-29 04:48 UTC, ianhanniballake approved these changes

2021-04-29 04:49 UTC, merged

2021-04-29 04:49 UTC, ianhanniballake commented
Thanks for making this change!